In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,10)

In [4]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2=np.arange(1,10).reshape(3,3)

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3= np.array([10,20,30,40,50])

In [10]:
arr3

array([10, 20, 30, 40, 50])

In [13]:
print("Shape of arr1", arr1.shape)
print("Shape of arr2", arr2.shape)
print("Shape of arr3", arr3.shape)

Shape of arr1 (9,)
Shape of arr2 (3, 3)
Shape of arr3 (5,)


In [15]:
print("Data type of arr1:", arr1.dtype)
print("Data type of arr2:", arr2.dtype)
print("Data type of arr3:", arr3.dtype)

Data type of arr1: int64
Data type of arr2: int64
Data type of arr3: int64
