Statistical functions

mean

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 3.5 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.6 MB 3.5 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.6 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 3.9 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.6 MB 3.9 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.6 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.6 MB 3.9 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.9 MB/s eta 0:00:01
   ----------

In [4]:
import numpy as np
array_data = np.round(np.random.random((4,4))*100).astype('int32')

In [6]:
array_data

array([[51, 95, 26, 66],
       [78, 69, 58, 20],
       [82, 93, 27, 82],
       [91, 88, 48, 66]], dtype=int32)

In [7]:
np.max(array_data,axis=0)

array([91, 95, 58, 82], dtype=int32)

In [8]:
np.max(array_data,axis=1)

array([95, 78, 93, 91], dtype=int32)

In [10]:
np.prod(array_data,axis=1)

array([ 8314020,  6243120, 16883964, 25369344])

mean

In [11]:
array_data

array([[51, 95, 26, 66],
       [78, 69, 58, 20],
       [82, 93, 27, 82],
       [91, 88, 48, 66]], dtype=int32)

In [12]:
np.mean(array_data)

np.float64(65.0)

In [14]:
np.mean(array_data,axis=1)

array([59.5 , 56.25, 71.  , 73.25])

In [15]:
np.mean(array_data,axis=0)

array([75.5 , 86.25, 39.75, 58.5 ])

std()

In [16]:
array_data

array([[51, 95, 26, 66],
       [78, 69, 58, 20],
       [82, 93, 27, 82],
       [91, 88, 48, 66]], dtype=int32)

In [17]:
np.std(array_data)

np.float64(23.950469723994978)

Median

In [18]:
np.median(array_data,axis=1)

array([58.5, 63.5, 82. , 77. ])

In [19]:
np.median(array_data)

np.float64(67.5)

var()===variance

In [21]:
np.var(array_data)

np.float64(573.625)