In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
numpy_array=np.array([1,2,3,4,5])

In [5]:
numpy_array

array([1, 2, 3, 4, 5])

In [6]:
TwoDArray=([[1,2,3],[4,5,6]])

In [7]:
TwoDArray

[[1, 2, 3], [4, 5, 6]]

In [8]:
ThreeDArray= ([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [9]:
ThreeDArray

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [10]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [12]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(4,13)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
np.arange(5,23,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21])

In [18]:
arange_data=np.arange(1,17)

In [19]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
np.ones([16])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
np.random.random((3,4))

array([[0.03333478, 0.07665638, 0.65590761, 0.91552869],
       [0.51767932, 0.47268756, 0.56868772, 0.52079366],
       [0.0466066 , 0.62386598, 0.97399829, 0.44083574]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

attribute

In [31]:
arr=np.array([1,2,3])

In [32]:
arr

array([1, 2, 3])

In [34]:
arr.ndim

1

In [35]:
arrayy=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [36]:
arrayy.ndim

3

In [37]:
array_elements=np.arange(5,57)

In [38]:
array_elements.size

52

In [40]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [41]:
np.array([[1,2],[3,4],[5,6]], dtype=np.int32).itemsize

4