In [2]:
import numpy as np

In [3]:
np.sin(0)

np.float64(0.0)

In [4]:
np.sin(60)

np.float64(-0.3048106211022167)

In [5]:
np.tan(45)

np.float64(1.6197751905438615)

In [11]:
matrix_1=np.round(np.random.random((3,4))*100).astype('int32')
matrix_2=np.round(np.random.random((4,3))*100).astype('int32')

In [8]:
matrix_1

array([[61, 54, 60, 86],
       [98, 44, 33, 22],
       [35, 55, 40, 50]], dtype=int32)

In [13]:
matrix_2

array([[63, 43, 53],
       [10,  9, 96],
       [34, 13, 98],
       [96, 14, 24]], dtype=int32)

In [14]:
np.dot(matrix_1,matrix_2)

array([[ 9749,  4939, 13995],
       [12191,  5039, 12347],
       [ 9319,  2885, 12891]], dtype=int32)

Log()

In [15]:
np.log(matrix_1)

array([[4.41884061, 4.06044301, 3.52636052, 3.36729583],
       [4.39444915, 3.8918203 , 2.94443898, 4.12713439],
       [3.04452244, 4.29045944, 3.49650756, 4.15888308]])

exp()

In [18]:
np.exp(matrix_1)

array([[1.11286375e+36, 1.54553894e+25, 5.83461743e+14, 3.93133430e+12],
       [1.50609731e+35, 1.90734657e+21, 1.78482301e+08, 8.43835667e+26],
       [1.31881573e+09, 5.05239363e+31, 2.14643580e+14, 6.23514908e+27]])

round()---> it helps with rounding off the float values to its nearest possible integer value

In [21]:
array=np.random.random((3,4))

In [23]:
array*10

array([[1.84607704, 9.90063544, 4.94400788, 6.87198889],
       [0.39607375, 2.40391913, 8.819201  , 4.36120206],
       [3.07154649, 7.63509164, 9.42571541, 0.6106072 ]])

In [24]:
np.round(array)

array([[0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.]])

In [26]:
np.ceil(array)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.floor(array)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Transpose()---> it calculate the transpose of the given matrix

In [30]:
np.transpose(array)

array([[0.1846077 , 0.03960738, 0.30715465],
       [0.99006354, 0.24039191, 0.76350916],
       [0.49440079, 0.8819201 , 0.94257154],
       [0.68719889, 0.43612021, 0.06106072]])

In [33]:
array=np.arange(1,13).reshape(3,4)

In [34]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Ravel()----> np.ravel()--->convert to nd to 1d aaray

In [36]:
array


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
array.ndim

2

In [38]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## indexing and slicing

In [39]:
array=np.round(np.random.random((5,5))*100).astype('int32')

In [40]:
array

array([[24, 13, 28, 29, 20],
       [45, 76, 65, 50, 24],
       [44, 91, 55, 33,  8],
       [36, 76, 95, 39,  4],
       [78, 37, 41,  0, 89]], dtype=int32)

In [41]:
array_one=np.arange(1,10)

In [42]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
array_one[6]

np.int64(7)

In [44]:
array

array([[24, 13, 28, 29, 20],
       [45, 76, 65, 50, 24],
       [44, 91, 55, 33,  8],
       [36, 76, 95, 39,  4],
       [78, 37, 41,  0, 89]], dtype=int32)

In [45]:
array[4,4]

np.int32(89)

In [46]:
 array_three=np.arange(1,9).reshape(2,2,2)

In [47]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
array_three[1,0,1]

np.int64(6)

In [49]:
array

array([[24, 13, 28, 29, 20],
       [45, 76, 65, 50, 24],
       [44, 91, 55, 33,  8],
       [36, 76, 95, 39,  4],
       [78, 37, 41,  0, 89]], dtype=int32)

In [50]:
array[2:4,3:5]

array([[33,  8],
       [39,  4]], dtype=int32)

In [51]:
array[2:,1:4]

array([[91, 55, 33],
       [76, 95, 39],
       [37, 41,  0]], dtype=int32)

In [52]:
array=np.arange(1,10)

In [53]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [54]:
array=np.arange(1,17).reshape(4,4)

In [55]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
for i in array:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [58]:
array=np.arange(1,28).reshape(3,3,3)

In [59]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
for i in array:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


## Stacking and Splitting

In [63]:
array_1=np.arange(1,13).reshape(3,4)

In [64]:
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
array_2=np.arange(13,25).reshape(3,4)

In [66]:
array_2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [68]:
horizantal_array=np.hstack((array_1,array_2))

In [69]:
horizantal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [73]:
vertical_array=np.vstack((array_1,array_2))

In [74]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [77]:
np.hsplit(vertical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [79]:
np.vsplit(vertical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]